
version: '3'
services:
  rabbitmq:
    build:
      context: ./
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  accepter:
    # image: python
    build: ./server
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./server/accepter:/app
      - ./server/MOM:/app/MOM
      - ./server/config.json:/config/config.json
    expose:
      - "8080"
    entrypoint: "python main.py"
    working_dir: /app
    depends_on:
      rabbitmq:
        condition: service_healthy

  general_aggregator1:
    # image: python
    build: ./server
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_ID=1
    volumes:
      - ./server/general_aggregator:/app
      - ./server/MOM:/app/MOM
      - ./server/config.json:/config/config.json
    expose:
      - "8080"
    entrypoint: "python main.py"
    working_dir: /app
    depends_on:
      rabbitmq:
        condition: service_healthy

  general_aggregator2:
    # image: python
    build: ./server
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_ID=2
    volumes:
      - ./server/general_aggregator:/app
      - ./server/MOM:/app/MOM
      - ./server/config.json:/config/config.json
    expose:
      - "8080"
    entrypoint: "python main.py"
    working_dir: /app
    depends_on:
      rabbitmq:
        condition: service_healthy

  likes_filter_views_sum1:
        # image: python
    build: ./server
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_ID=1
    volumes:
      - ./server/likes_filter_views_sum:/app
      - ./server/MOM:/app/MOM
      - ./server/config.json:/config/config.json
    expose:
      - "8080"
    entrypoint: "python main.py"
    working_dir: /app
    depends_on:
      rabbitmq:
        condition: service_healthy

  likes_filter_views_sum2:
        # image: python
    build: ./server
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_ID=2
    volumes:
      - ./server/likes_filter_views_sum:/app
      - ./server/MOM:/app/MOM
      - ./server/config.json:/config/config.json
    expose:
      - "8080"
    entrypoint: "python main.py"
    working_dir: /app
    depends_on:
      rabbitmq:
        condition: service_healthy

  client:
    image: python
    volumes:
      - ./client:/app
    command: python /app/main.py
    working_dir: /app
    depends_on:
      - accepter
