
version: '3'
services:
  rabbitmq:
    build:
      context: ./
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672

  accepter:
    # image: python
    build: ./server
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./server/accepter:/app
      - ./server/MOM:/app/MOM
      - ./server/config.json:/config/config.json
    expose:
      - "8080"
    entrypoint: "python main.py"
    working_dir: /app

  client:
    image: python
    volumes:
      - ./client:/app
    command: python /app/main.py
    working_dir: /app
    depends_on:
      - accepter
